version: '3.8'

services:
  app:
    build: .
    container_name: kenya-grace-hms
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

  # Optional: Local Postgres for testing
  db:
    image: postgres:15
    container_name: kenya-grace-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kenya_grace_hms
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
